const translations={
  en:{access:"ACCESS RESTRICTED",prelaunch:"PRE-LAUNCH SIGNAL",heroA:"SOMETHING",heroB:"IS COMING.",heroText:"A new standard for hardware shopping is almost online. You found the signal before the doors opened.",intercept:"INTERCEPT SIGNAL",core:"CORE SYSTEM",catalog:"CATALOGUE",public:"PUBLIC ACCESS",online:"ONLINE",classified:"CLASSIFIED",denied:"DENIED",feed:"PRODUCT FEED // CLASSIFIED",move:"MOVE TO REVEAL // LIMITED ACCESS",scroll:"SCROLL TO INTERCEPT",incoming:"INCOMING SIGNAL",whatA:"WHAT ARE WE",whatB:"BUILDING?",glimpse:"Just enough to know something serious is coming — not enough to spoil the launch.",card1Title:"BUILT FOR REAL SETUPS",card1Text:"From a first build to a serious upgrade, the experience is being shaped around the hardware people actually want.",card2Title:"FAST. CLEAR. TRUSTED.",card2Text:"Sharper discovery, clearer choices, and a storefront designed to feel as refined as the technology behind it.",card3Title:"MORE THAN A STORE",card3Text:"Launch is only the beginning. Elitedom is being built as a destination for hardware and technology.",behind:"BEHIND THE CURTAIN",systemA:"THE SYSTEM",systemB:"IS BOOTING.",systemText:"This page is only the signal. The full Elitedom experience stays behind the curtain until launch.",calibrating:"CALIBRATING",soon:"SOON",interrupted:"SIGNAL INTERRUPTED",enough:"YOU'VE SEEN ENOUGH.",dark:"The rest goes back into the dark until launch.",stay:"STAY TUNED",waitA:"THE WAIT WON'T",waitB:"BE LONG.",finalText:"When public access opens, this page disappears and Elitedom begins.",state:"CURRENT STATE",comingSoon:"COMING SOON",rights:"All rights reserved.",performance:"PERFORMANCE",hardware:"HARDWARE",gaming:"GAMING",power:"POWER",catGaming:"GAMING",catBuilds:"PC BUILDS",catComponents:"COMPONENTS",catPeripherals:"PERIPHERALS",catAudio:"AUDIO",catNetwork:"NETWORKING",bootSignal:"ESTABLISHING SECURE SIGNAL",launchControl:"LAUNCH CONTROL",encrypted:"ENCRYPTED"},
  ar:{access:"الدخول مقيّد",prelaunch:"إشارة ما قبل الإطلاق",heroA:"القادم",heroB:"مختلف.",heroText:"تجربة جديدة لشراء الهاردوير والتقنية تقترب من الانطلاق. وصلت إلى الإشارة قبل أن تُفتح الأبواب.",intercept:"تتبّع الإشارة",core:"النظام",catalog:"المنتجات",public:"الدخول العام",online:"جاهز",classified:"محجوب",denied:"مغلق",feed:"المنتجات // لم تُكشف بعد",move:"حرّك المؤشر للكشف // وصول محدود",scroll:"تابع الاستكشاف",incoming:"إشارة واردة",whatA:"ما الذي",whatB:"نُجهّزه؟",glimpse:"لمحة تكفي لتعرف أن القادم مختلف، من دون أن نفسد لحظة الإطلاق.",card1Title:"لتجميعتك القادمة",card1Text:"من أول تجميعة إلى أقوى ترقية، نصمم تجربة تساعدك على الوصول إلى الهاردوير المناسب بوضوح وثقة.",card2Title:"سرعة. وضوح. ثقة.",card2Text:"اختيارات مرتبة، تجربة سلسة، ومتجر صُمم ليواكب مستوى التقنية التي يقدمها.",card3Title:"أكثر من متجر",card3Text:"الإطلاق مجرد البداية. Elitedom يُبنى ليكون وجهتك المستمرة للهاردوير والتقنية.",behind:"خلف الكواليس",systemA:"المنظومة",systemB:"تستعد.",systemText:"ما تراه الآن مجرد إشارة. التجربة الكاملة ستظل خلف الستار حتى لحظة الإطلاق.",calibrating:"قيد التجهيز",soon:"قريبًا",interrupted:"انقطعت الإشارة",enough:"رأيت ما يكفي.",dark:"الباقي سيظل في الظل حتى يوم الإطلاق.",stay:"ترقّب",waitA:"الانطلاق",waitB:"أقرب مما تتوقع.",finalText:"عند فتح الأبواب، تختفي هذه الصفحة وتبدأ تجربة Elitedom.",state:"الحالة",comingSoon:"الإطلاق قريب",rights:"جميع الحقوق محفوظة.",performance:"أداء",hardware:"هاردوير",gaming:"ألعاب",power:"قوة",catGaming:"ألعاب",catBuilds:"تجميعات PC",catComponents:"مكوّنات",catPeripherals:"ملحقات",catAudio:"صوتيات",catNetwork:"شبكات",bootSignal:"تهيئة الإشارة الآمنة",launchControl:"مركز الإطلاق",encrypted:"مشفّر"}
};
const polish=document.createElement("link");polish.rel="stylesheet";polish.href="polish.css?v=1";document.head.appendChild(polish);
document.querySelectorAll('img[src="assets/logo-mark.png"]').forEach(img=>{img.src="assets/logo-mark.svg"});
const favicon=document.querySelector('link[rel="icon"]');if(favicon){favicon.href="assets/logo-mark.svg";favicon.type="image/svg+xml"}
const bootCopy=document.querySelector(".boot p"),terminalTitle=document.querySelector(".terminal__bar>span"),terminalEncrypted=document.querySelector(".terminal__bar>b");
const root=document.documentElement,body=document.body,toggle=document.getElementById("languageToggle"),reduced=matchMedia("(prefers-reduced-motion: reduce)").matches,fine=matchMedia("(pointer:fine)").matches;let lang=localStorage.getItem("elitedom-lang")||"en";
const redacted=document.getElementById("redactedWord");let redactIndex=0;const redactStates={en:["[REDACTED]","[LOCKED]","[SOON]","[REDACTED]"],ar:["[محجوب]","[مغلق]","[قريبًا]","[محجوب]"]};
function applyLanguage(next,animate=false){lang=next;const ar=lang==="ar";root.lang=lang;root.dir=ar?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(node=>{const value=translations[lang]?.[node.dataset.i18n];if(value)node.textContent=value});if(redacted){redactIndex=0;redacted.textContent=redactStates[lang][0]}if(toggle){toggle.textContent=ar?"EN":"AR";toggle.setAttribute("aria-label",ar?"Switch to English":"التبديل إلى العربية")}if(bootCopy)bootCopy.textContent=translations[lang].bootSignal;if(terminalTitle)terminalTitle.innerHTML=`<span dir="ltr">ELITEDOM //</span> ${translations[lang].launchControl}`;if(terminalEncrypted)terminalEncrypted.textContent=translations[lang].encrypted;localStorage.setItem("elitedom-lang",lang);if(animate){body.classList.remove("language-flash");void body.offsetWidth;body.classList.add("language-flash");setTimeout(()=>body.classList.remove("language-flash"),460)}}
toggle?.addEventListener("click",()=>applyLanguage(lang==="en"?"ar":"en",true));applyLanguage(lang);document.getElementById("year").textContent=new Date().getFullYear();
const boot=document.getElementById("boot");body.classList.add("locked");const releaseBoot=()=>{boot?.classList.add("done");body.classList.remove("locked")};window.addEventListener("load",()=>setTimeout(releaseBoot,reduced?60:540));setTimeout(releaseBoot,1900);
const revealObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add("visible");revealObserver.unobserve(entry.target)}}),{threshold:.12,rootMargin:"0px 0px -28px"});document.querySelectorAll(".reveal").forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i%4,3)*65}ms`;revealObserver.observe(el)});
const nav=document.getElementById("nav"),progress=document.getElementById("scrollProgress"),heroVisual=document.querySelector(".hero__visual"),cutRing=document.querySelector(".cut__ring");let scrollTick=false;function renderScroll(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;nav?.classList.toggle("is-scrolled",y>30);if(progress)progress.style.width=`${max>0?Math.min(100,y/max*100):0}%`;if(!reduced&&heroVisual)heroVisual.style.setProperty("--hero-shift",`${Math.min(28,y*.035)}px`);if(!reduced&&cutRing){const r=cutRing.parentElement.getBoundingClientRect();const delta=(innerHeight/2)-(r.top+r.height/2);cutRing.style.setProperty("--ring-shift",`${Math.max(-24,Math.min(24,delta*.035))}px`)}scrollTick=false}addEventListener("scroll",()=>{if(!scrollTick){requestAnimationFrame(renderScroll);scrollTick=true}},{passive:true});renderScroll();
const glow=document.getElementById("cursorGlow");if(fine&&!reduced&&glow){glow.style.opacity="1";addEventListener("pointermove",e=>{glow.style.left=`${e.clientX}px`;glow.style.top=`${e.clientY}px`},{passive:true})}
const vault=document.getElementById("hardwareVault");function setSpot(x,y){if(!vault)return;vault.style.setProperty("--spot-x",`${x}%`);vault.style.setProperty("--spot-y",`${y}%`)}if(vault){if(fine&&!reduced){vault.addEventListener("pointermove",e=>{const r=vault.getBoundingClientRect(),x=Math.max(0,Math.min(100,(e.clientX-r.left)/r.width*100)),y=Math.max(0,Math.min(100,(e.clientY-r.top)/r.height*100));setSpot(x,y);vault.style.transform=`perspective(1200px) rotateX(${(.5-y/100)*3.2}deg) rotateY(${(x/100-.5)*4.2}deg)`});vault.addEventListener("pointerleave",()=>{setSpot(68,45);vault.style.transform=""})}else if(!reduced){let t=0;(function drift(){t+=.009;setSpot(52+Math.sin(t)*29,45+Math.cos(t*.8)*18);requestAnimationFrame(drift)})()}vault.addEventListener("pointerdown",e=>{const r=vault.getBoundingClientRect();setSpot((e.clientX-r.left)/r.width*100,(e.clientY-r.top)/r.height*100);vault.classList.add("is-peeking");clearTimeout(vault._peekTimer);vault._peekTimer=setTimeout(()=>vault.classList.remove("is-peeking"),850)},{passive:true})}
document.querySelectorAll(".tilt-card").forEach(card=>{if(!fine||reduced)return;card.addEventListener("pointermove",e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;card.style.setProperty("--x",`${x*100}%`);card.style.setProperty("--y",`${y*100}%`);card.style.transform=`perspective(900px) rotateX(${(.5-y)*4}deg) rotateY(${(x-.5)*5}deg) translateY(-3px)`});card.addEventListener("pointerleave",()=>card.style.transform="")});
const magnetic=document.querySelector(".magnetic");if(magnetic&&fine&&!reduced){magnetic.addEventListener("pointermove",e=>{const r=magnetic.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2;magnetic.style.transform=`translate(${x*.07}px,${y*.1}px) translateY(-2px)`});magnetic.addEventListener("pointerleave",()=>magnetic.style.transform="")}
if(redacted&&!reduced){setInterval(()=>{redactIndex=(redactIndex+1)%redactStates[lang].length;redacted.classList.remove("glitch");void redacted.offsetWidth;redacted.textContent=redactStates[lang][redactIndex];redacted.classList.add("glitch")},2200)}
(function particles(){const canvas=document.getElementById("particles");if(!canvas||reduced)return;const ctx=canvas.getContext("2d"),dpr=Math.min(devicePixelRatio||1,2);let w=0,h=0,dots=[],raf=0;function resize(){w=innerWidth;h=innerHeight;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`;ctx.setTransform(dpr,0,0,dpr,0,0);const count=Math.min(74,Math.max(24,Math.floor(w*h/22000)));dots=Array.from({length:count},()=>({x:Math.random()*w,y:Math.random()*h,r:Math.random()*1.15+.2,vx:(Math.random()-.5)*.07,vy:-Math.random()*.075-.015,a:Math.random()*.24+.035}))}function frame(){ctx.clearRect(0,0,w,h);for(const d of dots){d.x+=d.vx;d.y+=d.vy;if(d.y<-8)d.y=h+8;if(d.x<-8)d.x=w+8;if(d.x>w+8)d.x=-8;ctx.beginPath();ctx.arc(d.x,d.y,d.r,0,Math.PI*2);ctx.fillStyle=`rgba(154,220,247,${d.a})`;ctx.fill()}raf=requestAnimationFrame(frame)}resize();frame();addEventListener("resize",resize,{passive:true});document.addEventListener("visibilitychange",()=>{if(document.hidden)cancelAnimationFrame(raf);else frame()})})();
